model:
  input_channels: 4
  input_length: 2048
  output_length: 1000
  dna_embedder_channels: 64
  num_groups: 8
  encoder_channels: [128, 192, 256]
  pool_size: 2
  decoder_channels: [256, 192, 128, 64]
  output_embedder_channels: 256
  embedding_projector:
    enabled: true
  norm_type: batch
  activation: gelu
  dropout: 0.1

  profile_head:
    source: decoder
    num_outputs: 2
    kernel_size: 75

  count_head:
    type: ynet
    source:
    conv_hidden_dims: [128, 64]
    mlp_hidden_dims: [64]
    kernel_size: 5
    pool_size: 2
    adaptive_pool_size: 4
    dropout: 0.1
    norm_type: batch
    mlp_norm_type: layer
    num_groups: 8

  bottleneck:
    type: hybrid_attention
    depth: 2
    kernel_size: 5
    dropout: 0.1
    norm_type: batch
    activation: gelu
    num_heads: 4
    attn_dropout: 0.1
    mlp_ratio: 2.0

dataset:
  input_length: 2048
  output_length: 1000
  max_jitter: 200
  reverse_complement: true
  use_dnase: true
  source_fracs: [0.875, 0.125]
  use_unmappability_mask: true
  seed: null

train:
  batch_size: 32
  learning_rate: 0.0005
  profile_loss_fn: MNLLLoss
  count_loss_fn: log1pMSELoss
  counts_weight: 100.0
  max_epochs: 500
  validation_iter: 100
  base_trainable: true
  precision: 32

early_stopping:
  patience: 20

checkpoint:
  save_top_k: 1
  filename: "{epoch:02d}-{valid_loss:.2f}"

dataloader:
  num_workers: 4
  prefetch_factor: 2
  pin_memory: true
  persistent_workers: true

lr_scheduler:
  scheduler_name: ReduceLROnPlateau
  scheduler_kwargs:
    mode: min
    factor: 0.5
    patience: 9
    min_lr: 1.0e-6
  lr_scheduler_kwargs:
    monitor: valid_loss
